image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build project
    init: |
      ./install-gatling.sh
      mvn -f ./rinhadebackend install
    command: |
      mvn -f ./rinhadebackend quarkus:dev

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - gatling.gatling
