image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build project
    init: |
      ./install-gatling.sh
      mvn -f ./rinhadebackend install
    command: |
      mvn -f ./rinhadebackend quarkus:dev

ports:
  - port: 5400
    visibility: private
    onOpen: ignore
  - port: 9000
    visibility: private
    onOpen: ignore
  - port: 9001
    visibility: private
    onOpen: ignore
  - port: 9002
    visibility: private
    onOpen: ignore
  - port: 9999
    visibility: public
    onOpen: ignore

vscode:
  extensions:
    - ritwickdey.liveserver
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - gatling.gatling

additionalRepositories:
  - url: https://github.com/zanfranceschi/rinha-de-backend-2024-q1