version: "3.5"

services:
  api01:
    image: caravanacloud/rinhadebackend:latest
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5400/rinha
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=123
    ports:
      - "9001:9990"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1.4"
          memory: "1500MB"

  api02:
    image: caravanacloud/rinhadebackend:latest
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5400/rinha
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=123
    ports:
      - "9002:9990"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "1.4"
          memory: "1500MB"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1.20"
          memory: "1000MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5400:5400"
    expose:
      - "5400"
    #    volumes:
    #      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -p 5400
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "1500MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
