version: "3.1"

services:
  api01:
    networks:
      - rinha-net
    image: caravanacloud/rinhadebackend-native:latest
    hostname: api01
    container_name: api01
    environment:
      - DB_HOSTNAME=db
      - QUARKUS_BANNER_ENABLED=false
#      - QUARKUS_HTTP_LIMITS_MAX_CONNECTIONS=60000
      - QUARKUS_HTTP_IDLE_TIMEOUT=45
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db:3306/rinha?useSSL=false&allowPublicKeyRetrieval=true
      - QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_MIN_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=60
      - QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT=60
#      - QUARKUS_DATASOURCE_JDBC_BACKGROUND_VALIDATION_INTERVAL=0
      - QUARKUS_DATASOURCE_USERNAME=rinha
      - QUARKUS_DATASOURCE_PASSWORD=123
      - QUARKUS_LOG_LEVEL=DEBUG
      - QUARKUS_LOG_CATEGORY__caravanacloud__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.quarkus__LEVEL=DEBUG
      - QUARKUS_LOG_CATEGORY__org.mysql__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.netty__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.vertx__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.jboss__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.flyway__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.smallreye__LEVEL=INFO
    ports:
      - "9001:9990"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api01:9990/_hc"]
      interval: 3s
      retries: 15
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "10MB"
  api02:
    networks:
      - rinha-net
    image: caravanacloud/rinhadebackend-native:latest
    hostname: api02
    container_name: api02
    environment:
      - DB_HOSTNAME=db
      - QUARKUS_BANNER_ENABLED=false
#      - QUARKUS_HTTP_LIMITS_MAX_CONNECTIONS=60000
      - QUARKUS_HTTP_IDLE_TIMEOUT=45
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://db:3306/rinha?useSSL=false&allowPublicKeyRetrieval=true
      - QUARKUS_DATASOURCE_JDBC_INITIAL_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_MIN_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_ACQUISITION_TIMEOUT=60
      - QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT=60
#      - QUARKUS_DATASOURCE_JDBC_BACKGROUND_VALIDATION_INTERVAL=0
      - QUARKUS_DATASOURCE_USERNAME=rinha
      - QUARKUS_DATASOURCE_PASSWORD=123
      - QUARKUS_LOG__LEVEL=DEBUG
      - QUARKUS_LOG_CATEGORY__caravanacloud__LEVEL=INFO
#      - QUARKUS_LOG_CATEGORY__io.quarkus__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.mysql__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.netty__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.vertx__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.jboss__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__org.flyway__LEVEL=INFO
      - QUARKUS_LOG_CATEGORY__io.smallreye__LEVEL=INFO
    ports:
      - "9002:9990"
    depends_on:
      db:
        condition: service_healthy
      api01:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api02:9990/_hc"]
      interval: 3s
      retries: 15
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "10MB"


  nginx:
    hostname: lb
    container_name: lb
    networks:
      - rinha-net 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    ports:
      - "9999:9999"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://lb:9999/_hc"]
      interval: 3s
      retries: 15
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "25MB"
  # mysql -hlocalhost -urinha -p123 rinha   
  db:
    networks:
      - rinha-net
    image: mysql:latest
    hostname: db
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=rinha
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=rinha
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306" 
    expose:
      - "3306"
    volumes:
      - ./init.mysql.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/my.cnf
    deploy:
      resources: 
        limits:
          cpus: "0.70"
          memory: "320MB"
    healthcheck:
      test: ["CMD", "sleep", "15"]
      interval: 3s
      retries: 15
      start_period: 10s


networks:
  rinha-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1000
